### ISSUE TITLE
Feature request. Set respawn radius center.

### ISSUE THREAD

**Issue by MadCowKastor** [LordTylus/SE-Torch-Plugin-ALE-RespawnFix#1]
I'd love to be able to move the center of the respawn radius. Trying to move the key elements such as planets and player built asteroid stations to the center of the map has proven very difficult.

**Comment by LordTylus** [comment]
Ahh yes that should be easy to implement. 

Probably gonna do it today.

**Comment by LordTylus** [comment]
You can now set the Center of the respawn area in your settings accordint to whatever you desire. 

You need at least Version 1.0.1.5 for that. 

![image](https://user-images.githubusercontent.com/22499516/78493475-75bf2300-7749-11ea-97be-353f2f13d01b.png)
